Story\AdminBundle\Document\Page:
    fields:
        id:
            id:  true
        pageName:
            type: string
        pageNumber:
            type: string
        body:
            type: string 
        decision:
            type: string