parameters:
#    story_security.example.class: Story\SecurityBundle\Example

services:
#    story_security.example:
#        class: %story_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
