story_view_front_end:
    resource: "@StoryViewFrontEndBundle/Resources/config/routing.yml"
    prefix:   /story

story_security:
    resource: "@StorySecurityBundle/Resources/config/routing.yml"
    prefix:   /

story_admin:
    resource: "@StoryAdminBundle/Resources/config/routing.yml"
    prefix:   /story-admin

web_forms_test:
    resource: "@WebFormsTestBundle/Resources/config/routing.yml"
    prefix:   /

