<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class StoryAdminBundleDocumentPageHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['pageName'])) {
            $value = $data['pageName'];
            $return = (string) $value;
            $this->class->reflFields['pageName']->setValue($document, $return);
            $hydratedData['pageName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['pageNumber'])) {
            $value = $data['pageNumber'];
            $return = (string) $value;
            $this->class->reflFields['pageNumber']->setValue($document, $return);
            $hydratedData['pageNumber'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['body'])) {
            $value = $data['body'];
            $return = (string) $value;
            $this->class->reflFields['body']->setValue($document, $return);
            $hydratedData['body'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['decision'])) {
            $value = $data['decision'];
            $return = (string) $value;
            $this->class->reflFields['decision']->setValue($document, $return);
            $hydratedData['decision'] = $return;
        }
        return $hydratedData;
    }
}