parameters:
#    story_admin.example.class: Story\AdminBundle\Example

services:
#    story_admin.example:
#        class: %story_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
