story_view_front_end_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: StoryViewFrontEndBundle:Default:index }

story_welcome:
    pattern:  /{storyId}
    defaults: { _controller: StoryViewFrontEndBundle:StoryRouter:storyHome }