parameters:
#    story_view_front_end.example.class: StoryView\FrontEndBundle\Example

services:
#    story_view_front_end.example:
#        class: %story_view_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
