Story\SecurityBundle\Document\AdminUser:
    fields:
        id:
            id:  true
        username:
            type: string
        password:
            type: string
        salt:
            type: string
        email:
            type: string
        isActive:
            type: boolean